### ISSUE TITLE
Pagination control is wrongly positioned on the survey list controller

### ISSUE THREAD

**Issue by olivierobert** [iSachdeva/SurveyApp#4]
<img width="375" alt="ios_simulator_-_iphone_6_-_iphone_6___ios_8_4__12h141_" src="https://cloud.githubusercontent.com/assets/696529/9064704/ec77ef06-3af7-11e5-9f04-442a8c67a4d1.png">

**Comment by iSachdeva** [comment]
Issues resolved in v1.2
